cutadapt/adapters.py, cutadapt/modifiers.py, tests/testadapters.py
* Moved code to create match info tuple to Match.get_info_record() (with test)
* In AdapterCutter.__call__, read.match_info is set by calling Match.get_info_record()
* In AdatperCutter._write_info, match info is retrieved from read.match_info
=> Store match_info in read, in preparation for moving I/O out of AdapterCutter

doc/guide.rst
Fix quality option spelling: the `--trim-qualities` option does not seem to exist:
> cutadapt: error: no such option: --trim-qualities
And:
```bash
⟩⟩⟩ cutadapt --help | fgrep -e '--trim-qualities' -e '--quality'
-q [5'CUTOFF,]3'CUTOFF, --quality-cutoff=[5'CUTOFF,]3'CUTOFF
--quality-base=QUALITY_BASE
```
=> Fix spelling in guide.rst

src/cutadapt/__main__.py
If this evaluates to string the xopen library will throw errors. Because `"1" in range(1,10) == False`
Since this is hidden there is no haste. I will use `-Z` for now. It is less explicit, but it works fine.
=> Add type for compression level

src/cutadapt/modifiers.py
Using both --action=lowercase and --pair-adapters resulted in a TypeError. The cause was a missing required positional argument. Upon investigation, the same missing argument was found for masked reads. This fixes both.
=> fix when combining non-default actions and paired adapters

CHANGES.rst, src/cutadapt/_align.pyx, tests/test_adapters.py
When a read contains a 5' adapter with a mismatch in the last nucleotide(s), the current alignment algorithm prefers to report these as deletions, resulting in the mismatched nucleotides not being trimmed from the read.
An example for how an alignment currently looks like (1 error allowed, 5' adapter):
```
adapter:  GCACATCT
read:     GCACATC- GGAA
```
With this, the read would be trimmed to `GGAA`, but that doesn’t make sense because this seems more likely:
```
adapter:  GCACATCT
read:     GCACATCG GAA
```
With this, the read would be trimmed to `GAA`.
The above example works with both anchored and regular 5' adapters, and something similar happens when *n* errors are allowed and the last *n* nucleotides are mismatches.
The reason for this is that both alignments have the same number of …
=> Fix for sometimes too short sequence trimmed

CHANGES.rst, doc/guide.rst, src/cutadapt/__main__.py, src/cutadapt/adapters.py, src/cutadapt/pipeline.py, src/cutadapt/report.py, tests/conftest.py, tests/test_command.py, tests/test_paired.py, tests/test_parser.py
=> Add support for dumping statistics in JSON format

src/cutadapt/__main__.py
Currently cutadapt opens external programs on the default setting, thus using more than 1 core by default. Even if cores is explicitly set to 1.
Cores ==0 does not help the situation.
EDIT: As shown in many many benchmarks. There is overhead to using multithreading. The best way to utilize a cluster is to open a multitude of single threaded processes. Cutadapt is fast enough to do this in reasonable time. 
EDIT2: A hidden flag that explicitly sets the xopen threads could be an alternative.
=> Force xopen to use the main thread  when cores==1

tox.ini
This should help us catch missing wheels on supported platforms, see #629. (No macOS wheels for dnaio available.)
This adds option `--only-binary :all:` to the `pip install` command. This also covers all the test dependencies (pytest etc.), and only listing non-test requirements would be more accurate, but the test requirements are all available as wheels, so it should be fine.
(I’m adding this now before uploading macOS wheels for dnaio to make sure that the test fails properly.)
=> Install all packages from wheels during tests

src/cutadapt/_align.pyx, src/cutadapt/_kmer_finder.pyi, src/cutadapt/_kmer_finder.pyx, src/cutadapt/_match_tables.py, src/cutadapt/adapters.py, src/cutadapt/kmer_heuristic.py, tests/test_kmer_finder.py, tests/test_kmer_heuristic.py, tox.ini
Alignment is the most cost effective way for approximately matching an adapter to a read sequence at the best possible position. The cost of this is alignment is proportional to the size of the adapter (m) multiplied by the length of the sequence (n). O(mn) cost means that the alignment is the most costly part of cutadapt.
There is however a subproblem that is much easier to solve: determining if an adapter is at all present in a sequence. If x errors are allowed, we can subdivide the adapter in x+1 pieces. It follows that at least one of the pieces must be present in the sequence without error. Modern search algorithms operate at a speed of near O(n) even for multiple pattern matching. When a sequence is determined not to be present in a read, alignment can be skipped. This results in a …
=> Add kmer heuristic for faster adapter matching

src/cutadapt/kmer_heuristic.py, tests/test_kmer_heuristic.py
Fixes #694 
This eliminates the exponential algorithm. This does not affect the speed of KmerFinder because it is oblivious to the number of patterns searched, as long as their combined length is smaller than a machine word.
The only disadvantage is an increase in the number of false positives:
before:
```
kmer    start   stop    considered sites        hit chance by random sequence (%)
AGA             -3      None    1       1.56
AGAT            -4      None    1       0.39
AGATC           -19     None    15      1.45
GGAAG           -19     None    15      1.45
AGATCGG         -33     None    27      0.16
AAGAGCA         -33     None    27      0.16
AACTCCAG        -33     None    26      0.04
CACGTCTG        -33     None    26      0.04
CACGTC          -29     None    24      0.58 …
```
=> Fix exponential runtime for longer adapters

src/cutadapt/qualtrim.pyx
Also includes a check if every phred score is in fact a valid phred score. By assigning the phreds to a uint8_t array, the `quals[i] - base` calculation is unsigned, and thus the result will always be positive. If the invalid character is a phred lower than 33, say 10, then it will map to 245. As a result we can check all phreds with only one check: are they higher than 93?
A lookup table is much faster than the expensive exponent calculations for floats. Especially since the lookup table will fit easily in L1-cache, the lookup time is at most ~3-4 clock cycles, which is hard to beat using arithmetic.
=> Speedup expected_errors by using a lookup table

src/cutadapt/_kmer_finder.pyi, src/cutadapt/_kmer_finder.pyx, tests/test_kmer_finder.py
Thanks again for replying to my e-mail. 
This PR holds the following changes:
- In the bitmatrix the empty columns have been made redundant by a slight reorganization of the search algorithm. Directly after the mask is applied, the check for a match is run, rather than after the shift operation. This holds the advantage that an adapter of 64 can always be fit in one word, regardless of how many individual pieces are needed due to the error rate.
- The value of 64 is hardcoded in one place and made available as a variable. This is used in tests.
- The SHIFT-OR algorithm was changed to SHIFT-AND for the following reasons:
+ SHIFT-OR does not have an advantage over SHIFT-AND. The zeroes that are shifted an are of no value as there are multiple words in one machine word and  there needs to be …
=> Utilize full length of the 64-bit word in the KmerFinder

CHANGES.rst, doc/algorithms.rst, doc/guide.rst, src/cutadapt/cli.py, src/cutadapt/pipeline.py, src/cutadapt/predicates.py, tests/test_predicates.py
I did some tests on GM24385_1.fastq.gz which is one of the nanopore GIAB samples. It has about 3 million records ranging from 3bp to over a million bp. 
`--max-ee` is unsuitable for this use case. A max-ee of 3 would be absolute garbage for the 3bp reads and stellar never seen before quality for the 1 million bp reads.
This pr adds a `--max-average-error-rate`/`--max-aer` option to alleviate this problem. Using a `--max-aer 0.1` option for instance to filter out the very worst long read sequencing reads seems like a decent practice.
I will be off until coming tuesday, so I won't be able to respond as promptly as I usually do. I hope you will consider this PR as it will make using cutadapt for long-read sequencing much more viable.
=> Add an option for maximum average error rate (--max-aer)

doc/conf.py
https://cutadapt.readthedocs.io/en/latest/ currently uses the default sphinx theme.
=> Attempt to fix the sphinx theme

src/cutadapt/expected_errors.h, src/cutadapt/qualtrim.pyx, tests/test_predicates.py
Hi Marcel,
It seems I made an error of judgement in #726. In that thread I state that single precision numbers is enough. That statement is incorrect, or a half-truth.
Since phred scores are between 0 and 93 they have only two significant decimal digits. Two decimal digits means 100 units, so that can be approached by a floating point number that has a significand of at least 7 bits significance. Floating point has 23 bits, so that is ample.
However this does not properly look at the calculation required to add two phred units. Single precision numbers have a 23-bit significand meaning that they can represent numbers that are 2^23 ~=  8 million units apart. Adding a phred of 0 to a phred of 70 (10 million units) is therefore barely possible. Adding a phred of 93 to a phred of 0 simply …
=> Make expected errors use doubles again for increased precision

src/cutadapt/_align.pyx
Hi a very simple PR. Currently the alignment inner loop contains a lot of pointer lookups. Therefore the compiler will always take the safe road. It cannot be sure if those pointers have been updated in the meantime.
This PR puts lookups that are guaranteed to stay the same in a certain scope in their own variable. This allows the compiler to do some nice optimizations (if it is able to spot some). 
I did take a look at the resulting assembler. Unfortunately I cannot provide any insights why as this might be faster.
The results:
before:
```
Benchmark 1: cutadapt -e 0.2 -a GCAATACGTAACTGAACGAAGTACAGG ~/test/nanopore_10000reads.fastq -o /dev/null
Time (mean ± σ):      4.643 s ±  0.063 s    [User: 4.567 s, System: 0.073 s]
Range (min … max):    4.571 s …  4.744 s    5 runs
```
After:
``` …
```
=> Follow best practices for pointer aliasing in alignment inner loop.

doc/reference.rst
I found issue https://github.com/marcelm/cutadapt/issues/302 that makes clear that `--info-file` does not currently fully support paired-end mode.
I suggest adding a little admonition to the docs to make this clear.  (Apologies if this information already exists somewhere in the docs -- I did a quick search but I couldn't find any mentions, aside from the above issue.)
=> Add admonition about info-file w/r/t paired end mode

src/cutadapt/report.py, tests/test_api.py
This is an alternative to #778.
@y9c, I made you a co-author on this to give you credit for the initial commit; I hope that is ok.
Closes #777
=> Allow multiple AdapterCutters and ReverseComplementers in a pipeline

src/cutadapt/expected_errors.h
The generic unrolled implementation performs similar to the SSE2 tuned code. This should make it faster on ARM platforms as well. In addition it is much easier to read.
```
Benchmark 1: cutadapt -o /dev/null  ~/test/5millionreads_R1.fastq
Time (mean ± σ):      4.958 s ±  0.135 s    [User: 4.554 s, System: 0.399 s]
Range (min … max):    4.786 s …  5.204 s    10 runs
Benchmark 1: cutadapt -o /dev/null --max-aer 0.01 ~/test/5millionreads_R1.fastq
Time (mean ± σ):      6.608 s ±  0.092 s    [User: 6.192 s, System: 0.410 s]
Range (min … max):    6.490 s …  6.800 s    10 runs
Benchmark 1: cutadapt -o /dev/null --max-aer 0.01 ~/test/5millionreads_R1.fastq
Time (mean ± σ):      6.612 s ±  0.132 s    [User: 6.197 s, System: 0.409 s]
Range (min … max):    6.357 s …  6.881 s    10 runs 
```
Just …
=> Simplify expected errors function

doc/installation.rst
The environment name is "cutadapt", not "cutadaptenv".
=> fix small typo in installation.rst

CHANGES.rst, doc/guide.rst, src/cutadapt/adapters.py, tests/test_adapters.py
This is a backwards-incompatible change, and therefore the version number will be bumped to 5.0.
This only applies when an index is used.
At index creation time, ambiguous sequences (those that would match two or more adapters equally well), are now *removed* from the index. That is, when they are encountered in a read, they will not be assigned to any adapter.
The intention is to reduce bias because we previously would report a match to one of the adapters (but which one was more or less randomly determined at index creation time).
=> Do not report a match for ambiguous sequences
